- updated for wanpipe-2.1.3
Changed files:
    wanrouter.init -> 1.2

diff --git a/wanrouter.init b/wanrouter.init
--- a/wanrouter.init
+++ b/wanrouter.init
@@ -6,11 +6,13 @@
 # description:  WANPIPE is a set of drivers and utilites for
 #		WAN router using Sangoma cards
 #		
+# $Revision$ $Date$
 
 # This script is changed for use with PLD and its rc-scripts
 #
 # It just initializes Sangoma cards now. Interfaces are configured
 # the same way as ethernet devices in PLD 
+
 # Source function library
 . /etc/rc.d/init.d/functions
 
@@ -84,24 +86,23 @@ router_load()
 	show "Starting WAN Router" ; started 
 	echo "`date`: starting WAN router" > $ROUTER_LOG
 
-	[ -f "$MOD1" ] || {
+	if [ ! -f "$MOD1" ]; then
 		mod_error $MOD1
 		return 1
-	}
-		
-        [ -f "$MOD2" ] || {
+	fi
+        if [ ! -f "$MOD2" ]; then
 		mod_error $MOD2 
                 return 1
-        }           
-        [ -f "$MOD3" ] || {
+        fi           
+        if [ ! -f "$MOD3" ]; then
 		mod_error $MOD3 
                 return 1
-        }          
+        fi          
 
-#	[ -f "$ROUTER_CONF" ] || {
-#		error "Configuration file $ROUTER_CONF not found"
-#		return 1
-#	}
+	wansock_config CHECK
+	if [ $? -eq 1 ]; then
+		return 1
+	fi
 
 	[ "$ROUTER_BOOT" = "NO" -o -z "$WAN_DRIVERS" ] && { 
 		echo -e "\n\nERROR in $ROUTER_RC file !!!" 
@@ -126,6 +127,8 @@ router_load()
 			deltext; fail
 		fi
 	done
+	
+	wansock_config LOAD
 	return 0
 }
 
@@ -152,6 +155,8 @@ router_unconfig()
 
 router_unload()
 {
+	wansock_config UNLOAD
+
 	for i in $WAN_DRIVERS
 	do lsmod | grep -wq $i && {
 		modprobe -r $i
@@ -211,7 +216,7 @@ print_active_devices()
 	cd $ROUTER_PROC
 	ac_list=`ls wanpipe*`;
 	for ac_wan in $ac_list; do
-		res=`grep "Device is not configured" $ROUTER_PROC/$ac_wan`
+		res=`grep "Device is not configured" $ROUTER_PROC/$ac_wan 2> /dev/null`
 		[ -z "$res" ] && {
 			echo -n "$ac_wan "
 		}
@@ -234,7 +239,7 @@ check_running ()
 
 	cd $ROUTER_PROC
 	
-	res=`grep "Device is not configured" $ROUTER_PROC/$device`
+	res=`grep "Device is not configured" $ROUTER_PROC/$device 2> /dev/null`
 	[ -z "$res" ] && {
 			#Device running
 			return 0
@@ -253,7 +258,7 @@ check_and_print_still_running ()
 	cd $ROUTER_PROC
 	WAN_LIST=`ls wanpipe*`	
 	for wan in $WAN_LIST; do
-		res=`grep "Device is not configured" $ROUTER_PROC/$wan`
+		res=`grep "Device is not configured" $ROUTER_PROC/$wan 2> /dev/null`
 		[ -z "$res" ] && {
 			echo "Devices still running:"
 			print_active_devices;
@@ -265,19 +270,200 @@ check_and_print_still_running ()
 	return 1
 }
 
+create_ft1_conf () {
+
+	local dev=$1
+	local res
+
+	wandev=`grep "wanpipe.*=" $WANPIPE_CONF_DIR/$dev.conf 2> /dev/null`
+	res=$?
+	if [ $res -eq 0 ]; then
+		wandev=${wandev%%=*}
+		check_bash
+		if [ $? -gt 1 ]; then
+			wandev=${wandev// /}
+		fi
+	else
+		echo -e "Error: Device name not found in $WANPIPE_CONF_DIR/$dev.conf\n"
+		exit 1
+	fi
+
+	wancpu=`grep "S514CPU.*=.*" -i $WANPIPE_CONF_DIR/$dev.conf 2> /dev/null`
+	wanslot=`grep "PCISLOT.*=.*" -i	$WANPIPE_CONF_DIR/$dev.conf 2> /dev/null`
+	wanio=`grep "IOPORT.*=.*" -i	$WANPIPE_CONF_DIR/$dev.conf 2> /dev/null`
+	wanirq=`grep "IRQ.*=.*" -i	$WANPIPE_CONF_DIR/$dev.conf 2> /dev/null`
+
+	if [ -z "$wancpu" -o -z "$wanslot" ]; then
+		if [ -z "$wanio" -o -z "$wanirq" ]; then
+			echo -e "Error: Missing fileds in $WANPIPE_CONF_DIR/$dev.conf" 
+			echo -e "       configuraton file, in [$wandev] section.\n " 
+			exit 1
+		fi
+	fi
+
+	cat <<EOM > $WANPIPE_CONF_DIR/$FT1_CONF
+
+#FT1 Configuration File
+#
+# Note: This file was automatically generated by wanrouter
+#       script. 
+#       DO NOT CHANGE IT
+#
+# CHDLC Protocol is used since, its firmware is the
+# only one with FT1 configuration functions.
+
+[devices]
+
+$wandev = WAN_CHDLC, Cisco HDLC Firmware  
+
+[$wandev]
+
+$wancpu
+$wanslot
+
+$wanio
+$wanirq
+
+Firmware        = $ROUTER_HOME/firmware/cdual514.sfm   # adapter firmware
+                                #
+                                # ----- Dual Port Memory Base Address --------
+#Memaddr        = 0xD0000       # Commenting this out enables Auto Memory
+                                # selection. Valid Memory addresses are:
+                                # 0xA0000,0xA2000...0xAE000 / 0xC0000,0xC2000...
+                                # 0xCE000 / 0xD0000,0xD2000...0xDE000 / 0xE0000,
+                                # 0xE2000...0xEE000   
+
+#--------------------- END OF FT1 CONFIGURATION ------------------------
+
+EOM
+
+}
+
+
+check_config_opt () 
+{
+	local dev=$1
+	local opt=$2
+
+	case $dev in
+
+	ft1_wanpipe*) 
+
+		#Strip off 'ft1_' from 'ft1_wanpipe#'
+		dev=${dev##ft1_}
+
+		#Check if wanpipe#.conf file exists
+		check_file "$WANPIPE_CONF_DIR/$dev.conf"
+		if [ $? -gt 0 ]; then
+			exit 1
+		fi
+
+		#If we are starting the router up, create
+		#the ft1.conf file in $WANPIPE_CONF_DIR directory
+		if [ $opt -eq 0 ]; then
+			create_ft1_conf $dev
+		fi
+
+		#Return string ft1
+		result "ft1" 
+
+		#Get the wanpipe device number, and return it
+                #as a return code. This indicates that we want
+                #to setup ft1 device
+		dev=${dev##wanpipe}
+		check_bash
+		if [ $? -gt 1 ]; then
+			dev=${dev// /}
+		fi
+		return $dev
+		;;
+	
+	wanpipe*) 
+		#Check if wanpipe#.conf file exists
+		check_file "$WANPIPE_CONF_DIR/$dev.conf"
+		if [ $? -gt 0 ]; then
+			exit 1
+		fi
+
+		#return string wanpipe#
+		result $dev
+
+		#return zero which indicates that we
+		#want to startup reglar wanpipe device
+		#not ft1 device
+		return 0
+		;;
+
+	*)
+		#Illegal syntax obtained
+		echo "Error: Incorrect device name syntax !"
+		exit 1
+		;;
+	esac
+
+}
+
+check_ft1_config ()
+{
+	local ft1=$1
+
+	if [ $ft1 = ft1 ]; then
+		return 0
+	else
+		return 1
+	fi
+}
+
+result () {
+	echo $1 > $RC
+}
+
+wansock_config ()
+{
+	local opt=$1
+	local kver
+
+	kver=$(uname -r)
+	kver=`echo $kver | cut -d'.' -f2 2> /dev/null`
+
+	if [ $kver -eq 0 ]; then
+		return 0
+	fi
+	
+	if [ $opt = UNLOAD ]; then
+		lsmod | grep -wq "$AF_WANPIPE" && {
+			modprobe -r $AF_WANPIPE
+		}
+	elif [ $opt = LOAD ]; then
+		modprobe $AF_WANPIPE
+	else
+		if [ ! -f "$MOD4" ]; then
+			mod_error "$MOD4"
+			return 1
+		fi
+	fi
+	return 0
+}
 ####### MAIN #################################################################
 # set -x
 
 export PATH=/sbin:/bin:/usr/sbin:/usr/bin
-ROUTER_VERSION=2.1.1
+ROUTER_VERSION=2.1.3
 ROUTER_RC=/etc/sysconfig/wanrouter
 ROUTER_HOME=/usr/lib/wanrouter
 SCRIPT=wanrouter
 ROUTER_PROC=/proc/net/wanrouter
 WAN_DRIVERS=wanpipe
+AF_WANPIPE=af_wanpipe
 MOD1=/lib/modules/$(uname -r)/misc/wanrouter.o
 MOD2=/lib/modules/$(uname -r)/net/wanpipe.o
 MOD3=/lib/modules/$(uname -r)/net/sdladrv.o
+MOD4=/lib/modules/$(uname -r)/misc/af_wanpipe.o
+
+# Return code 
+RC=$(pwd)/return_code
+GET_RC="cat $RC"
+FT1_CONF=ft1.conf
 
 # Ignore interrupt signals.
 trap '' 2
@@ -323,7 +509,17 @@ case "$1" in
 		else
 		#ROUTER START WANPIPE
 
+			[ -f $WANPIPE_CONF_DIR/$FT1_CONF ] && rm -f $WANPIPE_CONF_DIR/$FT1_CONF
 			dev=$2
+
+			#Parse the dev name, and if it starts with
+			#ft1 than it means we should load the ft1 
+ 			#driver.  
+			check_config_opt $dev 0
+			ft1_or_wanpipe=$?
+			dev=$($GET_RC)
+			rm -f $RC
+
 			ROUTER_CONF=$WANPIPE_CONF_DIR/$dev.conf
 
 			check_file $ROUTER_CONF || exit 1
@@ -332,23 +528,50 @@ case "$1" in
 				router_load && touch $ROUTER_LOCK
 			}	
 
-			res=`grep "Device is not configured" $ROUTER_PROC/$dev`
-			[ -z "$res" ] && {
+			#If we are starting FT1 driver, we have to check
+			#wether the actual wanpipe# device is running or
+                        #not, thus name dev has to be changed to 'wanpipe#'
+			if [ $ft1_or_wanpipe -gt 0 ]; then
+				dev="wanpipe$ft1_or_wanpipe"
+			fi 
+
+			res=`grep "Device is not configured" $ROUTER_PROC/$dev 2> /dev/null`
+			if [ -z "$res" ]; then
 				echo "Device $dev is still running"
 				echo -e "Run wanrouter stop $dev first\n"
 				exit 1
-			}
+			fi
 		
-			#Configure a separate WANPIPE device
-			show "Starting up device: $dev" ; busy
-			echo "Starting up device: $dev" >> $ROUTER_LOG
+			#Since we changed the name of dev above,
+			#we must check if we are running ft1 device,
+                        #output a correct message	
+			if [ $ft1_or_wanpipe -gt 0 ]; then
+				show "Starting up device: $dev, FT1 config mode" ; busy
+				echo "Starting up device: $dev, FT1 config mode" >> $ROUTER_LOG
+			else
+				show "Starting up device: $dev" ; busy
+				echo "Starting up device: $dev" >> $ROUTER_LOG
+			fi
 			router_config $ROUTER_CONF
+			if [ $? -ne 0 ]; then
+				deltext; fail
+				exit 3
+			fi
+			
+			#When loading ft1 device there are not interfaces
+			if [ $ft1_or_wanpipe -eq 0 ]; then
+				interf_config $dev $ROUTER_CONF
+				if [ $? -ne 0 ]; then
+					deltext; fail
+					exit 4
+				fi
+			fi
 			deltext; ok
 		fi
 		;;
 	stop)	
 		
-		#ROUTER STOP
+		#WANROUTER STOP
 		if [ -z $2 ]; then
 
 			#Check that all wanpipe#.conf file defined in 
@@ -356,6 +579,7 @@ case "$1" in
 			check_config || exit 1
 
 			[ ! -f "$ROUTER_LOCK" -o ! -d "$ROUTER_PROC" ] && {
+				router_unload
 				echo -e "Router is already stopped !\n"
 				exit 1
 			}
@@ -364,7 +588,7 @@ case "$1" in
                         #device is running first
 			for dev in $WAN_DEVICES; do
 				ROUTER_CONF=$WANPIPE_CONF_DIR/$dev.conf
-				check_running $dev || continue
+				check_running $dev || exit 1
 			done
 
 			#Stop all routers but check if device
@@ -389,30 +613,51 @@ case "$1" in
 			router_unload
 
 		else
-		#ROUTER STOP WANPIPE
+		#WANROUTER STOP WANPIPE
 
 			dev=$2
 			ROUTER_CONF=$WANPIPE_CONF_DIR/$dev.conf
+
+			check_config_opt $dev 1
+			ft1_or_wanpipe=$?
+			dev=$($GET_RC)
+			rm -f $RC
 
 			#Check that all configuration files exist
 			check_file $ROUTER_CONF || exit 1
 
 			#Check that modules are up and running
 			[ ! -f "$ROUTER_LOCK" -o ! -d "$ROUTER_PROC" ] && {
+				router_unload
 				echo -e "Router is already stopped !\n";
 				exit 1;
 			}
 
+			#If we are stopping FT1 driver, we have to check
+			#wheter the actual wanpipe# device is running or
+                        #not, thus name dev has to be changed to 'wanpipe#'
+			if [ $ft1_or_wanpipe -gt 0 ]; then
+				dev="wanpipe$ft1_or_wanpipe"
+			fi 
 
 			#Check that device is running first
-			check_running $dev || {
-					echo -e "Device $dev is already stopped\n"
-					exit 0;
+			if [ $ft1_or_wanpipe -eq 0 ]; then
+				check_running $dev || {
+						echo -e "Error: Device $dev is already stopped\n"
+						exit 0;
 					}
+			fi
 
-			#Bring down the interface and router
-			show "Shutting down device: $dev" ; busy
-			echo "Shutting down device: $dev" >> $ROUTER_LOG
+			if [  $ft1_or_wanpipe -gt 0 ]; then
+				show "Shutting down device: $dev, FT1 config mode" ; busy
+				echo "Shutting down device: $dev, FT1 config mode" >> $ROUTER_LOG
+			else	
+				show "Shutting down device: $dev" ; busy
+				echo "Shutting down device: $dev" >> $ROUTER_LOG
+			fi
+			
+			[ -f $WANPIPE_CONF_DIR/$FT1_CONF ] && rm -f $WANPIPE_CONF_DIR/$FT1_CONF
+			
 			router_unconfig $ROUTER_CONF
 			deltext ; ok
 
@@ -433,12 +678,12 @@ case "$1" in
 		
 		[ -f "$ROUTER_LOCK" ] || {
 				echo -e "Router is stopped !\n";
-				exit 1;
+				exit 0;
 		}
 		
 		echo -e "Devices currently active:"
 		print_active_devices;
-		exit 1;
+		exit 0;
 
 		;;
 	*)	echo -e "\nWAN Router startup script"
@@ -452,5 +697,6 @@ case "$1" in
 		echo -e "                               (# can range from 1 to 16)\n"
 		echo -e " 	wanrouter status : List all active devices\n"
 		exit 1
+		;;
 esac
 exit 0
